version: "3"
services:
    dtc1:
        build: ./dtc1
        environment:
            SA_PASSWORD: "Sql2019isfast"
            ACCEPT_EULA: "Y"
            MSSQL_AGENT_ENABLED: "true"
            MSSQL_RPC_PORT: 135
            MSSQL_DTC_TCP_PORT: 51999
        ports:
            - "1401:1433"
            - "135:135"
            - "51999:51999"
        container_name: dtc1
        hostname: dtc1
    dtc2:
        build: ./dtc2
        environment:
            SA_PASSWORD: "Sql2019isfast"
            ACCEPT_EULA: "Y"
            MSSQL_AGENT_ENABLED: "true" 
            MSSQL_RPC_PORT: 135
            MSSQL_DTC_TCP_PORT: 51999
        ports:
            - "1402:1433"
            - "136:135"
            - "51998:51999"
        container_name: dtc2
        hostname: dtc2


