---
apiVersion: v1

kind: ServiceAccount

metadata:
  name: manual-failover


---
apiVersion: rbac.authorization.k8s.io/v1

kind: Role

metadata:
  name: manual-failover

rules:
- resources: ["configmaps"]
  apiGroups: [""]
  verbs: ["get", "update"]
  resourceNames: 
- resources: ["endpoints"]
  apiGroups: [""]
  verbs: ["get"]
  resourceNames: 
- resources: ["pods"]
  apiGroups: [""]
  verbs: ["list"]


---
apiVersion: rbac.authorization.k8s.io/v1

kind: RoleBinding

metadata:
  name: manual-failover
  namespace: 

roleRef:
  name: manual-failover
  apiGroup: rbac.authorization.k8s.io
  kind: Role

subjects:
- name: manual-failover
  kind: ServiceAccount


---
apiVersion: batch/v1

kind: Job

metadata:
  name: manual-failover
  namespace: 

spec:
  template:
    metadata:
      name: manual-failover
    spec:
      serviceAccount: manual-failover
      restartPolicy: Never
      containers:
