---
apiVersion: v1

kind: ServiceAccount

metadata:
  name: mssql-operator
  namespace:


---
apiVersion: rbac.authorization.k8s.io/v1

kind: ClusterRole

metadata:
  name: mssql-operator

rules:
- resources: ["serviceaccounts", "services"]
  apiGroups: [""]
  verbs: ["create", "get", "update", "delete"]
- resources: ["jobs"]
  apiGroups: ["batch"]
  verbs: ["create", "get", "update", "delete"]
- resources: ["roles","rolebindings"]
  apiGroups: ["rbac.authorization.k8s.io"]
  verbs: ["create", "get", "update", "delete"]
- resources: ["statefulsets"]
  apiGroups: ["apps"]
  verbs: ["create", "delete", "get", "update"]
- resources: [ "configmaps", "endpoints", "secrets"]
  apiGroups: [""]
  verbs: ["create", "get", "update", "watch", "delete"]
- resources: ["pods"]
  apiGroups: [""]
  verbs: ["get", "list", "update"]
- resources: ["customresourcedefinitions"]
  apiGroups: ["apiextensions.k8s.io"]
  verbs: ["create"]
- resources: ["customresourcedefinitions"]
  apiGroups: ["apiextensions.k8s.io"]
  resourceNames: ["sqlservers.mssql.microsoft.com"]
  verbs: ["delete", "get", "update"]
- resources: ["sqlservers"]
  apiGroups: ["mssql.microsoft.com"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1

kind: ClusterRoleBinding

metadata:
  name: mssql-operator

roleRef:
  name: mssql-operator
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole

subjects:
- name: mssql-operator
  namespace:
  kind: ServiceAccount


---
apiVersion: apps/v1beta2

kind: Deployment

metadata:
  name: mssql-operator
  namespace: 

spec:
  selector:
    matchLabels:
      app: mssql-operator
  replicas: 1
  template:
    metadata:
      labels:
        app: mssql-operator
    spec:
      serviceAccount: mssql-operator
      containers: []
