---
apiVersion: mssql.microsoft.com/v1
kind: SqlServer
metadata:
  name: 
  namespace: default
  labels:
    type: sqlservr
    name:
spec:

  sqlServerContainer:
    image: mcr.microsoft.com/mssql/server:2019-CTP2.1-ubuntu

  saPassword:
    secretKeyRef:
      name: sql-secrets
      key: sapassword

  acceptEula: true

  availabilityGroups:
  - ag1

---
apiVersion: v1
kind: Service
metadata:
  name:
  namespace:
spec:
  ports:
  - name: tds
    port: 1433
  selector:
    name:
    type: sqlservr
  type: LoadBalancer
